apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lingolou
  namespace: lingolou
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.lingolou.app
      secretName: lingolou-tls
  rules:
    - host: www.lingolou.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lingolou
                port:
                  number: 80
