apiVersion: v1
kind: PersistentVolume
metadata:
  name: lingolou-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  azureFile:
    secretName: azure-files-secret
    shareName: lingolou-data
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lingolou-data
  namespace: lingolou
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  volumeName: lingolou-data-pv
  resources:
    requests:
      storage: 5Gi
